// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"context"
	"database/sql"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"

	"github.com/NFhbar/mull/internal/store"
)

// ApprovalEventSig is keccak256("Approval(address,address,uint256)").
const ApprovalEventSig = "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"

type Approval struct {
	Owner   common.Address
	Spender common.Address
	Value   *big.Int
}

var approvalArgs abi.Arguments

func init() {
	typeOf := func(s string) abi.Type {
		t, err := abi.NewType(s, "", nil)
		if err != nil {
			panic(fmt.Sprintf("codegen: bad abi type %q: %v", s, err))
		}
		return t
	}
	approvalArgs = abi.Arguments{
		{Type: typeOf("uint256"), Name: "value", Indexed: false},
	}
}

func DecodeApproval(log store.Event) (Approval, error) {
	var out Approval
	if len(log.Topics) < 3 {
		return out, fmt.Errorf("Approval: need 3 topics, got %d", len(log.Topics))
	}
	if common.HexToHash(log.Topics[0]) != common.HexToHash(ApprovalEventSig) {
		return out, fmt.Errorf("Approval: topic0 mismatch: %s", log.Topics[0])
	}
	out.Owner = common.HexToAddress(log.Topics[1])
	out.Spender = common.HexToAddress(log.Topics[2])
	data := common.FromHex(log.Data)
	vals, err := approvalArgs.Unpack(data)
	if err != nil {
		return out, fmt.Errorf("Approval: unpack data: %w", err)
	}
	if len(vals) != 1 {
		return out, fmt.Errorf("Approval: expected 1 non-indexed values, got %d", len(vals))
	}
	if v, ok := vals[0].(*big.Int); ok {
		out.Value = v
	} else {
		return out, fmt.Errorf("Approval: value: unexpected type %T", vals[0])
	}
	return out, nil
}

type approvalSink struct {
	db *sql.DB
}

func newApprovalSink(db *sql.DB) *approvalSink {
	return &approvalSink{db: db}
}

func (s *approvalSink) SinkID() string { return "Approval" }

func (s *approvalSink) Topic0() string { return ApprovalEventSig }

func (s *approvalSink) Handle(ctx context.Context, e store.Event) error {
	if len(e.Topics) == 0 || common.HexToHash(e.Topics[0]) != common.HexToHash(ApprovalEventSig) {
		return nil
	}
	v, err := DecodeApproval(e)
	if err != nil {
		return err
	}
	_, err = s.db.ExecContext(ctx,
		`INSERT OR IGNORE INTO events_erc20_approval (source, block_number, tx_hash, log_index, "owner", "spender", "value") VALUES (?, ?, ?, ?, ?, ?, ?)`,
		e.Source, e.BlockNumber, e.TxHash, e.LogIndex, v.Owner.Hex(), v.Spender.Hex(), bigIntStr(v.Value),
	)
	return err
}

func (s *approvalSink) RewindTo(ctx context.Context, source string, block uint64) error {
	_, err := s.db.ExecContext(ctx, `DELETE FROM events_erc20_approval WHERE source = ? AND block_number >= ?`, source, block)
	return err
}
