// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"encoding/hex"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

func bigIntStr(x *big.Int) string {
	if x == nil {
		return "0"
	}
	return x.String()
}

func hexEncode(b []byte) string {
	return "0x" + hex.EncodeToString(b)
}

func decodeBigIntTopic(topic string) *big.Int {
	out := new(big.Int)
	out.SetBytes(common.FromHex(topic))
	return out
}

func decodeBoolTopic(topic string) bool {
	b := common.FromHex(topic)
	for _, c := range b {
		if c != 0 {
			return true
		}
	}
	return false
}
