// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"encoding/hex"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

func bigIntStr(x *big.Int) string {
	if x == nil {
		return "0"
	}
	return x.String()
}

func hexEncode(b []byte) string {
	return "0x" + hex.EncodeToString(b)
}

func decodeBigIntTopic(topic string) *big.Int {
	out := new(big.Int)
	out.SetBytes(common.FromHex(topic))
	return out
}

// decodeSignedBigIntTopic decodes a Solidity-signed integer topic word using
// two's-complement sign extension. The unsigned helper above sees 0xff..ff as
// 2^256-1; for intN we instead return -1 by subtracting 1<<bits when the sign
// bit is set.
func decodeSignedBigIntTopic(topic string, bits int) *big.Int {
	out := new(big.Int)
	out.SetBytes(common.FromHex(topic))
	if out.Bit(bits-1) == 1 {
		mod := new(big.Int).Lsh(big.NewInt(1), uint(bits))
		out.Sub(out, mod)
	}
	return out
}

func decodeBoolTopic(topic string) bool {
	b := common.FromHex(topic)
	for _, c := range b {
		if c != 0 {
			return true
		}
	}
	return false
}

// decodeFixedBytesTopic returns a byte slice of length at least n decoded from
// the topic, zero-padding the tail when common.FromHex yields a short slice
// (malformed hex, odd length, etc.). The caller converts to [N]byte; without
// this guard, [N]byte(common.FromHex(badTopic)) would panic and abort the
// indexer goroutine instead of producing a recoverable zero value — matching
// the silent-zero behavior of the sibling helpers.
func decodeFixedBytesTopic(topic string, n int) []byte {
	b := common.FromHex(topic)
	if len(b) >= n {
		return b
	}
	out := make([]byte, n)
	copy(out, b)
	return out
}
