// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"database/sql"

	"github.com/NFhbar/mull/internal/store"
)

func NewSinks(db *sql.DB) []store.EventSink {
	return []store.EventSink{
		newApprovalSink(db),
		newTransferSink(db),
	}
}
