// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"context"
	"database/sql"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"

	"github.com/NFhbar/mull/internal/store"
)

// TransferEventSig is keccak256("Transfer(address,address,uint256)").
const TransferEventSig = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"

type Transfer struct {
	From  common.Address
	To    common.Address
	Value *big.Int
}

var transferArgs abi.Arguments

func init() {
	typeOf := func(s string) abi.Type {
		t, err := abi.NewType(s, "", nil)
		if err != nil {
			panic(fmt.Sprintf("codegen: bad abi type %q: %v", s, err))
		}
		return t
	}
	transferArgs = abi.Arguments{
		{Type: typeOf("uint256"), Name: "value", Indexed: false},
	}
}

func DecodeTransfer(log store.Event) (Transfer, error) {
	var out Transfer
	if len(log.Topics) < 3 {
		return out, fmt.Errorf("Transfer: need 3 topics, got %d", len(log.Topics))
	}
	if common.HexToHash(log.Topics[0]) != common.HexToHash(TransferEventSig) {
		return out, fmt.Errorf("Transfer: topic0 mismatch: %s", log.Topics[0])
	}
	out.From = common.HexToAddress(log.Topics[1])
	out.To = common.HexToAddress(log.Topics[2])
	data := common.FromHex(log.Data)
	vals, err := transferArgs.Unpack(data)
	if err != nil {
		return out, fmt.Errorf("Transfer: unpack data: %w", err)
	}
	if len(vals) != 1 {
		return out, fmt.Errorf("Transfer: expected 1 non-indexed values, got %d", len(vals))
	}
	if v, ok := vals[0].(*big.Int); ok {
		out.Value = v
	} else {
		return out, fmt.Errorf("Transfer: value: unexpected type %T", vals[0])
	}
	return out, nil
}

type transferSink struct {
	db *sql.DB
}

func newTransferSink(db *sql.DB) *transferSink {
	return &transferSink{db: db}
}

func (s *transferSink) SinkID() string { return "Transfer" }

func (s *transferSink) Topic0() string { return TransferEventSig }

func (s *transferSink) Handle(ctx context.Context, e store.Event) error {
	if len(e.Topics) == 0 || common.HexToHash(e.Topics[0]) != common.HexToHash(TransferEventSig) {
		return nil
	}
	v, err := DecodeTransfer(e)
	if err != nil {
		return err
	}
	_, err = s.db.ExecContext(ctx,
		`INSERT OR IGNORE INTO events_erc20_transfer (block_number, tx_hash, log_index, "from", "to", "value") VALUES (?, ?, ?, ?, ?, ?)`,
		e.BlockNumber, e.TxHash, e.LogIndex, v.From.Hex(), v.To.Hex(), bigIntStr(v.Value),
	)
	return err
}

func (s *transferSink) RewindTo(ctx context.Context, block uint64) error {
	_, err := s.db.ExecContext(ctx, `DELETE FROM events_erc20_transfer WHERE block_number >= ?`, block)
	return err
}
