package codegen

const docTemplate = `// Code generated by mull codegen; DO NOT EDIT.
package gen
`

const schemaTemplate = `// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"context"
	"database/sql"
)

const SchemaDDL = ` + "`" + `{{range $i, $e := .}}{{if $i}}

{{end}}CREATE TABLE IF NOT EXISTS {{$e.TableName}} (
    source       TEXT    NOT NULL,
    block_number INTEGER NOT NULL,
    tx_hash      TEXT    NOT NULL,
    log_index    INTEGER NOT NULL,
{{range $e.AllFields}}    "{{.ColName}}" {{.SQLType}} NOT NULL,
{{end}}    PRIMARY KEY (source, tx_hash, log_index)
);{{end}}` + "`" + `

func ApplySchema(ctx context.Context, db *sql.DB) error {
	if SchemaDDL == "" {
		return nil
	}
	_, err := db.ExecContext(ctx, SchemaDDL)
	return err
}
`

const sinksTemplate = `// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"database/sql"

	"github.com/NFhbar/mull/internal/store"
)

func NewSinks(db *sql.DB) []store.EventSink {
{{- if . }}
	return []store.EventSink{
{{- range . }}
		new{{.Name}}Sink(db),
{{- end }}
	}
{{- else }}
	_ = db
	return nil
{{- end }}
}
`

const helpersTemplate = `// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"encoding/hex"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

func bigIntStr(x *big.Int) string {
	if x == nil {
		return "0"
	}
	return x.String()
}

func hexEncode(b []byte) string {
	return "0x" + hex.EncodeToString(b)
}

func decodeBigIntTopic(topic string) *big.Int {
	out := new(big.Int)
	out.SetBytes(common.FromHex(topic))
	return out
}

// decodeSignedBigIntTopic decodes a Solidity-signed integer topic word using
// two's-complement sign extension. The unsigned helper above sees 0xff..ff as
// 2^256-1; for intN we instead return -1 by subtracting 1<<bits when the sign
// bit is set.
func decodeSignedBigIntTopic(topic string, bits int) *big.Int {
	out := new(big.Int)
	out.SetBytes(common.FromHex(topic))
	if out.Bit(bits-1) == 1 {
		mod := new(big.Int).Lsh(big.NewInt(1), uint(bits))
		out.Sub(out, mod)
	}
	return out
}

func decodeBoolTopic(topic string) bool {
	b := common.FromHex(topic)
	for _, c := range b {
		if c != 0 {
			return true
		}
	}
	return false
}

// decodeFixedBytesTopic returns a byte slice of length at least n decoded from
// the topic, zero-padding the tail when common.FromHex yields a short slice
// (malformed hex, odd length, etc.). The caller converts to [N]byte; without
// this guard, [N]byte(common.FromHex(badTopic)) would panic and abort the
// indexer goroutine instead of producing a recoverable zero value — matching
// the silent-zero behavior of the sibling helpers.
func decodeFixedBytesTopic(topic string, n int) []byte {
	b := common.FromHex(topic)
	if len(b) >= n {
		return b
	}
	out := make([]byte, n)
	copy(out, b)
	return out
}
`

const eventTemplate = `// Code generated by mull codegen; DO NOT EDIT.
package gen

import (
	"context"
	"database/sql"
	"fmt"
{{- if .HasBigInt }}
	"math/big"
{{- end }}

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"

	"github.com/NFhbar/mull/internal/store"
)

// {{.Name}}EventSig is keccak256("{{.SigText}}").
const {{.Name}}EventSig = "{{.SigHash}}"

type {{.Name}} struct {
{{- range .AllFields }}
	{{.Name}} {{.GoType}}
{{- end }}
}

{{ if .NonIndexedArgs }}var {{.FileBase}}Args abi.Arguments

func init() {
	typeOf := func(s string) abi.Type {
		t, err := abi.NewType(s, "", nil)
		if err != nil {
			panic(fmt.Sprintf("codegen: bad abi type %q: %v", s, err))
		}
		return t
	}
	{{.FileBase}}Args = abi.Arguments{
{{- range .NonIndexedArgs }}
		{Type: typeOf("{{.SolType}}"), Name: "{{.ColName}}", Indexed: false},
{{- end }}
	}
}
{{ end }}
func Decode{{.Name}}(log store.Event) ({{.Name}}, error) {
	var out {{.Name}}
	if len(log.Topics) < {{ len .IndexedArgs | plus1 }} {
		return out, fmt.Errorf("{{.Name}}: need {{ len .IndexedArgs | plus1 }} topics, got %d", len(log.Topics))
	}
	if common.HexToHash(log.Topics[0]) != common.HexToHash({{.Name}}EventSig) {
		return out, fmt.Errorf("{{.Name}}: topic0 mismatch: %s", log.Topics[0])
	}
{{- range .IndexedArgs }}
	out.{{.Name}} = {{.TopicExpr}}
{{- end }}
{{- if .NonIndexedArgs }}
	data := common.FromHex(log.Data)
	vals, err := {{.FileBase}}Args.Unpack(data)
	if err != nil {
		return out, fmt.Errorf("{{.Name}}: unpack data: %w", err)
	}
	if len(vals) != {{ len .NonIndexedArgs }} {
		return out, fmt.Errorf("{{.Name}}: expected {{ len .NonIndexedArgs }} non-indexed values, got %d", len(vals))
	}
{{- range $i, $arg := .NonIndexedArgs }}
	if v, ok := vals[{{$i}}].({{$arg.GoType}}); ok {
		out.{{$arg.Name}} = v
	} else {
		return out, fmt.Errorf("{{$.Name}}: {{$arg.ColName}}: unexpected type %T", vals[{{$i}}])
	}
{{- end }}
{{- end }}
	return out, nil
}

type {{.FileBase}}Sink struct {
	db *sql.DB
}

func new{{.Name}}Sink(db *sql.DB) *{{.FileBase}}Sink {
	return &{{.FileBase}}Sink{db: db}
}

func (s *{{.FileBase}}Sink) SinkID() string { return "{{.Name}}" }

func (s *{{.FileBase}}Sink) Topic0() string { return {{.Name}}EventSig }

func (s *{{.FileBase}}Sink) Handle(ctx context.Context, e store.Event) error {
	if len(e.Topics) == 0 || common.HexToHash(e.Topics[0]) != common.HexToHash({{.Name}}EventSig) {
		return nil
	}
	v, err := Decode{{.Name}}(e)
	if err != nil {
		return err
	}
	_, err = s.db.ExecContext(ctx,
		` + "`" + `INSERT OR IGNORE INTO {{.TableName}} (source, block_number, tx_hash, log_index{{ range .AllFields }}, "{{.ColName}}"{{end}}) VALUES (?, ?, ?, ?{{ range .AllFields }}, ?{{end}})` + "`" + `,
		e.Source, e.BlockNumber, e.TxHash, e.LogIndex{{ range .AllFields }}, {{.BindExpr}}{{end}},
	)
	return err
}

func (s *{{.FileBase}}Sink) RewindTo(ctx context.Context, source string, block uint64) error {
	_, err := s.db.ExecContext(ctx, ` + "`" + `DELETE FROM {{.TableName}} WHERE source = ? AND block_number >= ?` + "`" + `, source, block)
	return err
}
`
